#!/bin/sh -e

case "$1" in
	install)
		;;

	upgrade)
		invoke-rc.d --quiet cfengine3 stop || true
		;;

	abort-upgrade)
		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

if [ install = "$1" -o upgrade = "$1" ]; then

	# Copy old workdir to new workdir
	if [ ! -e "/var/lib/cfengine" ]; then
		if [ -d "/var/cfengine" ]; then
			mv -f /var/cfengine /var/lib/cfengine
		elif [ -d "/var/lib/cfengine3" ]; then
			mv -f /var/lib/cfengine3 /var/lib/cfengine
		fi
	fi

	# Create backups of old workdirs
	if [ -d "/var/lib/cfengine" ]; then
		if [ ! -h "/var/cfengine" ]; then
			mv -f /var/cfengine /var/cfengine.dpkg-bak
		fi
		if [ ! -h "/var/lib/cfengine3" ]; then
			mv -f /var/lib/cfengine3 /var/lib/cfengine3.dpkg-bak
		fi
	fi
fi

